name: Deploy SA Framework to DEV
'on':
  push:
    branches:
      - qa

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 (Build)
        run: |
          pwd
          whoami
          echo "Hello Test pipline!"
